### PR TITLE
Captions

### PR DESCRIPTION
**Pull request by gdamore**
This address some more customizable captioning stuff.

### CODE REVIEW

**Comment by xcoulon** [comment]
@gdamore looks good, thanks! Would you mind squashing the PR into a single commit? Each commit has its own title:
```
* feature(renderer): Customizable caption prefix.
* compat(renderer): table-caption and table-number handling wrong
* feature(renderer): Example blocks should support custom captions
```
which commit msg do you want to have? or do you want to split into 3 PRs?

**Comment by gdamore** [comment]
I was trying to keep them separate per your earlier request.  The commits stand alone but a single PR seems adequate to me.  I am no longer at my computer tonight but if you still want then squashed in the morning then I will be happy to do so.  (Or feel free to do so yourself.)

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by xcoulon** [comment]
> I was trying to keep them separate per your earlier request. The commits stand alone but a single PR seems adequate to me. I am no longer at my computer tonight but if you still want then squashed in the morning then I will be happy to do so. (Or feel free to do so yourself.) 

hmm, I could actually enable and use the "rebase and merge" option to keep these 3 commits separated. I'll check that

**Comment by xcoulon** [comment]
> > I was trying to keep them separate per your earlier request. The commits stand alone but a single PR seems adequate to me. I am no longer at my computer tonight but if you still want then squashed in the morning then I will be happy to do so. (Or feel free to do so yourself.)
> 
> hmm, I could actually enable and use the "rebase and merge" option to keep these 3 commits separated. I'll check that

cool, it worked ;)

**Pull request merged**
