### PR TITLE
Support for thematic break elements

### PR DESCRIPTION
**Pull request by gdamore**
This PR is based on PR #636 and contains it's commit.  It should be merged after wards (only the final commit).

### CODE REVIEW

**Comment by gdamore** [comment]
Coverage is going to be nigh impossible to cover without creating some special templates that force a failure.  Its the usual case of any error case coverage testing.

**Comment by xcoulon** [comment]
> Coverage is going to be nigh impossible to cover without creating some special templates that force a failure. Its the usual case of any error case coverage testing.

yes, it's fine, no worries ;)

**Comment by xcoulon** [comment]
@gdamore could you rebase your PR?

**Comment by gdamore** [comment]
Rebased now.

**Comment by xcoulon** [comment]
thanks @gdamore! 🙌

**Pull request merged**
